services:
  - type: web
    name: yes-native-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: "*"
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
